# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [1]:
# !pip install numpy
import numpy as np

In [2]:
# Assignment 1: Array Creation and Manipulation

# 1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. 

import numpy as np
arr1= np.random.randint(1,21, size=(5,5))
print(arr1)
print("\n")

# Replace all the elements in the third column with 1.
arr1[2:3] = 1
print(arr1)



[[18 19 10 12 18]
 [15 17  8  3  3]
 [10  2  5  9  7]
 [16  8 15 19 10]
 [ 4 10  2  2  1]]


[[18 19 10 12 18]
 [15 17  8  3  3]
 [ 1  1  1  1  1]
 [16  8 15 19 10]
 [ 4 10  2  2  1]]


In [3]:
# 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.
arr2 = np.random.randint(1,17, size = (4,4))
print(arr2)
print("\n")

np.fill_diagonal(arr2, 0)
print(arr2)

[[ 2  3 10  2]
 [ 5 15  7  5]
 [ 9 12  9 11]
 [15  5 10  4]]


[[ 0  3 10  2]
 [ 5  0  7  5]
 [ 9 12  0 11]
 [15  5 10  0]]


In [4]:
### Assignment 2: Array Indexing and Slicing

# 1. Create a NumPy array of shape (6, 6) with values from 1 to 36. 
# Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

arr3 = np.random.randint(1,37, size=(6,6))

print(arr3)

print("\n")

sub_arr = arr3[2:5, 1:4]

print(sub_arr)

[[26 11 36 24 20 14]
 [26  9 21 24 23 19]
 [11 14 11 18 31 13]
 [19 16  5 32  6 31]
 [33  4 14 15  8 36]
 [ 5 10 31 17 34  5]]


[[14 11 18]
 [16  5 32]
 [ 4 14 15]]


In [5]:
# 2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.
arr4 = np.random.randint(1,37, size=(5,5))
print(arr4)
print("\n")
border_elemet = np.concatenate((arr4[0], arr4[-1], arr4[1:-1, 0], arr4[1:-1, -1]))
print(border_elemet)

[[ 2 31 28 35 16]
 [ 8 15 24  5 21]
 [24 20 18 24 28]
 [10 29 18 12 24]
 [ 7 26  5 33 32]]


[ 2 31 28 35 16  7 26  5 33 32  8 24 10 21 28 24]


In [6]:
### Assignment 3: Array Operations

# 1. Create two NumPy arrays of shape (3, 4) filled with random integers. 
# Perform element-wise addition, subtraction, multiplication, and division.
arr5= np.random.randint(1,11, size=(3,4))
arr6 = np.random.randint(1,11, size=(3,4))

print(arr5)
print(arr6)
print("ADDITION")
print(np.add(arr5, arr6))
print("SUBTRACT")
print(np.subtract(arr5, arr6))
print("MULTIPLY")
print(np.multiply(arr5, arr6))
print("DIVIDE")
print(np.divide(arr5, arr6))

[[ 1  8 10  6]
 [ 7  9  3  1]
 [ 1  1  3  3]]
[[ 7  2  3  6]
 [ 7  9  9  4]
 [ 6  6  3 10]]
ADDITION
[[ 8 10 13 12]
 [14 18 12  5]
 [ 7  7  6 13]]
SUBTRACT
[[-6  6  7  0]
 [ 0  0 -6 -3]
 [-5 -5  0 -7]]
MULTIPLY
[[ 7 16 30 36]
 [49 81 27  4]
 [ 6  6  9 30]]
DIVIDE
[[0.14285714 4.         3.33333333 1.        ]
 [1.         1.         0.33333333 0.25      ]
 [0.16666667 0.16666667 1.         0.3       ]]


In [7]:
# 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. 
arr7 = np.random.randint(1,17, size=(4,4))
print("Original Array: \n")
print(arr7)

# Compute the row-wise and column-wise sum.
row_wise = np.sum(arr7, axis=1)
print("Row Wise Sum: ", row_wise)
column_wise = np.sum(arr7, axis= 0)
print("Column Wise Sum: ", column_wise)

Original Array: 

[[ 2  8 16  1]
 [ 9  7  7 14]
 [15  9 16 11]
 [11 15  2  1]]
Row Wise Sum:  [27 37 51 29]
Column Wise Sum:  [37 39 41 27]


In [8]:
## Assignment 4: Statistical Operations

# 1. Create a NumPy array of shape (5, 5) filled with random integers. 
# Compute the mean, median, standard deviation, and variance of the array.

arr8 = np.random.randint(1,11,size=(5,5))
mean = np.mean(arr8)
print("Mean: ",mean)

sd = np.std(arr8)
print("Standard Deviation: ",sd)

variance = np.var(arr8)
print("Variance: ", variance)



Mean:  5.44
Standard Deviation:  2.4992798962901297
Variance:  6.246400000000001


In [9]:
# 2. Create a NumPy array of shape (3, 3) with values from 1 to 9. 
# Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).
#normalization = arr- mean/ std_dev

arr9 = np.random.randint(1,10,size=(3,3))
print("Original array: ")
print(arr9)


mean = np.mean(arr9)
std_dev = np.std(arr9)

normalization = (arr9 - mean) / std_dev
print("Normalized data: ", normalization)

Original array: 
[[2 5 3]
 [4 5 3]
 [4 5 9]]
Normalized data:  [[-1.29188448  0.29361011 -0.76338629]
 [-0.23488809  0.29361011 -0.76338629]
 [-0.23488809  0.29361011  2.4076029 ]]


In [10]:
### Assignment 5: Broadcasting

# 1. Create a NumPy array of shape (3, 3) filled with random integers. 
# Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
arr10 = np.random.randint(1, 11, size=(3,3))
print("Original array: \n")
print(arr10)

print("\n")

arr11 = np.array([10, 10, 10])
print("1 D array: \n")
print(arr11)

print("\n")
final = arr10 + arr11
print("Resulting Array: \n")
print(final)

Original array: 

[[4 8 9]
 [9 5 8]
 [9 3 1]]


1 D array: 

[10 10 10]


Resulting Array: 

[[14 18 19]
 [19 15 18]
 [19 13 11]]


In [11]:
# 2. Create a NumPy array of shape (4, 4) filled with random integers.
#  Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.
arr12 = np.random.randint(1, 11, size=(4,4))
print("Original Array: \n")
print(arr12)

arr13 = np.random.randint(1, 11, size=(4,))
print("1D array: \n")
print(arr13)

sub = arr12 - arr13
print("Resulting Array: \n")
print(sub)


Original Array: 

[[ 9  2  7  1]
 [ 8  7 10  6]
 [ 7 10  6  6]
 [ 1  5  6  4]]
1D array: 

[ 7  6 10 10]
Resulting Array: 

[[ 2 -4 -3 -9]
 [ 1  1  0 -4]
 [ 0  4 -4 -4]
 [-6 -1 -4 -6]]


In [12]:
### Assignment 6: Linear Algebra

# 1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
arr14 = np.random.randint(1, 11, size=(3,3))
print("Original Array: \n")
print(arr14)

determinant = np.linalg.det(arr14)
inverse = np.linalg.inv(arr14)
eigenvalues = np.linalg.eigvals(arr14)

print("Determinant of the Array: \n", determinant)
print("\n")
print("Inverse of the Array: \n", inverse)
print("\n")
print("Eigenvalues of the Array:\n ", eigenvalues)
print("\n")


Original Array: 

[[1 9 5]
 [8 2 9]
 [2 6 8]]
Determinant of the Array: 
 -231.99999999999997


Inverse of the Array: 
 [[ 0.1637931   0.18103448 -0.30603448]
 [ 0.19827586  0.00862069 -0.13362069]
 [-0.18965517 -0.05172414  0.30172414]]


Eigenvalues of the Array:
  [16.74246504 -7.57239791  1.82993287]




In [13]:
# 2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.
arr15 = np.random.randint(1, 11, size=(2,3))
arr16 = np.random.randint(1, 11, size=(3,2))

print("Array 1: \n")
print(arr15)

print("Array 2 : \n")
print(arr16)

multi = arr15 @ arr16
print('Resulting Array: \n')
print(multi)

Array 1: 

[[2 5 4]
 [6 4 7]]
Array 2 : 

[[3 1]
 [4 9]
 [4 2]]
Resulting Array: 

[[42 55]
 [62 56]]


In [14]:
### Assignment 7: Advanced Array Manipulation

# 1. Create a NumPy array of shape (3, 3) with values from 1 to 9. 
# Reshape the array to shape (1, 9) and then to shape (9, 1).
arr17 = np.random.randint(1, 10, size=(3,3))
print("Original Array: \n")
print(arr17)

print("\n")

reshape1 = arr17.reshape((1,9))
print("Reshaped Array 1: \n")
print(reshape1)

print("\n")

reshape2 = reshape1.reshape((9,1))
print("Reshaped Array 2: \n")
print(reshape2)


Original Array: 

[[1 7 1]
 [1 3 5]
 [2 1 1]]


Reshaped Array 1: 

[[1 7 1 1 3 5 2 1 1]]


Reshaped Array 2: 

[[1]
 [7]
 [1]
 [1]
 [3]
 [5]
 [2]
 [1]
 [1]]


In [15]:
# 2. Create a NumPy array of shape (5, 5) filled with random integers. 
# Flatten the array and then reshape it back to (5, 5).

arr18 = np.random.randint(1, 11, size= (5,5))
print("Original Array: ")
print(arr18)

flat_array = arr18.flatten()
print("Flattened Array: ")
print(flat_array)

reshape = flat_array.reshape((5,5))
print("Array reshaped in (5,5): ")
print(reshape)

Original Array: 
[[ 9  4  6 10  7]
 [ 5  9  2  3  6]
 [ 8  3  1  6  7]
 [ 9  4  7  3  5]
 [ 2  8  6  4  6]]
Flattened Array: 
[ 9  4  6 10  7  5  9  2  3  6  8  3  1  6  7  9  4  7  3  5  2  8  6  4
  6]
Array reshaped in (5,5): 
[[ 9  4  6 10  7]
 [ 5  9  2  3  6]
 [ 8  3  1  6  7]
 [ 9  4  7  3  5]
 [ 2  8  6  4  6]]


In [16]:
## Assignment 8: Fancy Indexing and Boolean Indexing

# 1. Create a NumPy array of shape (5, 5) filled with random integers. 
# Use fancy indexing to extract the elements at the corners of the array.
arr19 = np.random.randint(1, 11, size=(5,5))
print("Original array: \n")
print(arr19)

corner = arr19[ [0, 0, -1, -1],[0, -1, 0, -1]]
print(corner)


Original array: 

[[ 4  7 10  5 10]
 [ 6  4  3  4  2]
 [ 8  3  1  7 10]
 [ 1  5  5  8  7]
 [ 6  9  4  5  5]]
[ 4 10  6  5]


In [17]:
# 2. Create a NumPy array of shape (4, 4) filled with random integers. 
# Use boolean indexing to set all elements greater than 10 to 10.
arr = np.random.randint(1, 11, size=(4,4))
print("Original array: \n")
print(arr)

arr[arr > 10] = 10
print("Modified Array: \n")
print(arr)

Original array: 

[[ 3  6  6 10]
 [ 4  6  3  8]
 [ 1  2  4  6]
 [ 2  1  4  6]]
Modified Array: 

[[ 3  6  6 10]
 [ 4  6  3  8]
 [ 1  2  4  6]
 [ 2  1  4  6]]


In [18]:
### Assignment 9: Structured Arrays

# 1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). 
# Add some data and sort the array by age.
import numpy as np
dt= np.dtype([('name', (np.str_, 10)), ('age', np.int32), ('weight', np.float64)]) 
a = np.array([('Sana', 2, 21.0), ('Mansi', 7, 29.0)],  dtype=dt)
print("Original Array: \n")
print(a)

sorted = np.sort(a, order='age')
print("Sorted Array on the basis of age: \n")
print(sorted)

Original Array: 

[('Sana', 2, 21.) ('Mansi', 7, 29.)]
Sorted Array on the basis of age: 

[('Sana', 2, 21.) ('Mansi', 7, 29.)]


In [19]:
# 2. Create a structured array with fields 'x' and 'y' (both integers). 
# Add some data and compute the Euclidean distance between each pair of points.
field_dt= np.dtype([('x', np.int32), ('y', np.int32)]) 
arr20 = np.array([( 2, 3), (4,5), (8,9)],  dtype=field_dt)

distances = np.linalg.norm(arr20[:, np.newaxis] - arr20, axis=2)
print(distances)


UFuncTypeError: ufunc 'subtract' did not contain a loop with signature matching types (dtype([('x', '<i4'), ('y', '<i4')]), dtype([('x', '<i4'), ('y', '<i4')])) -> None

In [ ]:
## Assignment 10: Masked Arrays
import numpy.ma as ma

# 1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. 
# Compute the sum of the unmasked elements.
arr21 = np.random.randint(1, 21, size= (4,4))
masked_array = ma.masked_greater(arr21, 10)

print("Original array: ")
print(arr21)
print("\n")
print("Masked Array: ")
print(masked_array)
print("\n")
sum_array = masked_array.sum()
print("Sum Array of Masked Array: ")
print(sum_array)

Original array: 
[[ 2 18 17 13]
 [20 13 18 18]
 [16 18 13  8]
 [ 4 18 17  5]]


Masked Array: 
[[2 -- -- --]
 [-- -- -- --]
 [-- -- -- 8]
 [4 -- -- 5]]


Sum Array of Masked Array: 
19


In [ ]:
# 2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. 
# Replace the masked elements with the mean of the unmasked elements.
arr22 = np.random.randint(1, 21, size= (3,3))
masked_array = ma.masked_greater(arr22, )